# Generated by Django 2.1.7 on 2019-03-24 02:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 24, 11, 25, 50, 169467)),
        ),
    ]
