# Generated by Django 2.1.7 on 2019-03-24 03:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20190324_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 24, 12, 21, 18, 585638)),
        ),
        migrations.AlterField(
            model_name='category',
            name='owner',
            field=models.CharField(max_length=200),
        ),
    ]
