# Generated by Django 2.2.6 on 2019-10-25 08:55

from django.db import migrations, models
import django.db.models.deletion
import recipes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('ingredients', '0001_initial'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=300)),
                ('level', models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('E', 'Expert')], default='B', max_length=1)),
                ('is_template', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.Category')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('timer', models.IntegerField(default=-1)),
                ('type', models.CharField(choices=[('BASIC', recipes.models.DetailType('BASIC')), ('FERMENTATION', recipes.models.DetailType('FERMENTATION')), ('DOUGH', recipes.models.DetailType('DOUGH')), ('OVEN', recipes.models.DetailType('OVEN'))], default=recipes.models.DetailType('BASIC'), max_length=50)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeTools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tools.Tools')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeDetailsIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=20)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ingredients.Ingredient')),
                ('recipe_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.RecipeDetails')),
            ],
        ),
    ]
