# Generated by Django 2.2.6 on 2019-10-25 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_auto_20191025_0436'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeDetailsIngredients',
            new_name='RecipeDetailsIngredient',
        ),
    ]
