# Generated by Django 2.1.7 on 2019-03-14 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_auto_20190314_2354'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tool',
            new_name='Tools',
        ),
    ]
